terminatorlib/terminal.py
Older Vte versions only offer the old implementation.
fixes #10
=> terminal: Add compat detection for Vte regexp feature

MANIFEST.in, setup.py, terminator.wrapper
We don't really need this file, if one needs to wrap the binary they could use `$HOME/bin/terminator`
Anyone thoughts on this?
=> Remove obsolete terminator.wrapper

terminatorlib/keybindings.py, terminatorlib/terminator.py, terminatorlib/window.py
This is so that terminator will run natively on MacOS using the quartz backend, rather than requiring the X11 backend.
=> Only import GdkX11 when available

INSTALL
Now, FreeBSD ports of terminator uses the source from here.
Please add FreeBSD into the list.
Since FreeBSD is not Linux,  I omitted the word 'Linux' :-)
=> Add FreeBSD

terminatorlib/terminal.py
From https://bugzilla.redhat.com/show_bug.cgi?id=1830452  Dragging and dropping from a file manager didn't work and generated a traceback.  I was pretty sure this was part of the stuff from my original patch, but maybe that was missed.  I think this also fixes dragging and dropping a link from a browser.
Just checked, and yes, dragging and dropping links from a browser was also broken and this patch fixes it.
=> fix traceback on dragging and dropping files from a file manager

terminatorlib/terminal.py
It's a weird feature that I've never heard of but in the titlebar menu in the top left corner there's two menu items "Insert terminal number" and "Insert padded terminal number".  These were not previously working and would just put the following to stdout.  This PR fixes this issue.
```
Traceback (most recent call last):
File "/home/mattrose/Code/terminator/terminatorlib/terminator.py", line 642, in do_enumerate
term.feed(numstr % (idx + 1))
File "/home/mattrose/Code/terminator/terminatorlib/terminal.py", line 1541, in feed
self.vte.feed_child(text, len(text))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
```
=> fix exception when feeding terminal number to terminal

terminator
The layout launcher crashing with an error upon attempting to select a layout.
```
$ ./terminator -s
```
Then select a layout, and this crash happens:
```
Traceback (most recent call last):
File "/home/fernando/Projects/terminator/terminatorlib/layoutlauncher.py", line 87, in on_row_activated
self.launch_layout()
File "/home/fernando/Projects/terminator/terminatorlib/layoutlauncher.py", line 100, in launch_layout
spawn_new_terminator(self.terminator.origcwd, ['-u', '-l', layout])
File "/home/fernando/Projects/terminator/terminatorlib/util.py", line 335, in spawn_new_terminator
cmd = os.path.join (cwd, sys.argv[0])
File "/usr/lib/python3.8/posixpath.py", line 76, in join
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
‘LayoutLauncher’ needs to know …
=> Fix layout launcher error

po/ckb.po, po/en_AU.po, po/en_CA.po, po/en_GB.po, po/es.po, po/fy.po, po/nl.po, po/oc.po, po/ru_RU.po, po/si.po, po/tyv.po, po/zh_CN.po, po/zh_TW.po
So, some of the language files (I think the oldest ones from the early 2000s) have an empty "Language:" section of the .po file.  msgfmt deals with this just fine, but the library I'm planning to replace it with (Babel) doesn't deal with that, and throws an exception
File "/usr/local/lib/python3.8/site-packages/babel/core.py", line 1094, in parse_locale
raise ValueError('expected only letters, got %r' % lang)
=> fix up language strings in .po files

terminatorlib/layoutlauncher.glade
The Layout Launcher initial window is too small, especially the height.
This commit makes it a little larger by default:
=> Make LayoutLauncher window a little larger by default

.authors.footer, .authors.header, .mailmap, AUTHORS, RELEASE.md
This is an approach to mention everyone contributing to Terminator.
=> Update AUTHORS with a full list from GIT history

INSTALL.md
It seems that the nightly ppa is not available any more for Ubuntu so I have to install it from source and I found these pieces are missing from the `INSTALL.md` file.
I am setting up the terminator to be executed on a ubuntu 16 docker container. Maybe was that the reason I needed `dbus-x11`??
=> update the INSTALL.md for Ubuntu installation

INSTALL.md
Perhaps I should remove this link altogether?
=> Gentoo: github is only a mirror

terminatorlib/cwd.py, terminatorlib/terminal.py, terminatorlib/terminator.py
This fixes a regression introduced in 40ba659f6d19001b964f72390153b81e33e1908a
=> Fix fallback for getting the current working directory

terminatorlib/terminal_popup_menu.py
I often want to launch a layout, but can't remember what the keyboard shortcut is. This patch adds it to the right-click popup menu.
Older patch on Launchpad:
https://bugs.launchpad.net/terminator/+bug/1800735
=> Add layout launcher to terminal popup menu.

terminatorlib/terminal.py
If there is only one active tab, terminator should not consume tab-select events.
Those should instead be propagated, so they can be used by other programs "further down the line". Tab switch keybindings are often shared with terminal programs like WeeChat and irssi that also implement tabs.
=> Propagate tab-swictch events if there is only one tab

terminatorlib/regex.py
While browsing the issues and the source code I encountered this TODO. After some searching I found where the constants are documented and defined. I have added the references to the source code as comments.
=> Fix TODO for documenting vte regex matching constants

terminatorlib/ipc.py
In a situation where we have all of the dbus libraries installed, but there is no dbus server available, for whatever reason (see bug #65 for one), don't crash, just proceed without dbus
This is actually a pretty rare situation, but I can see this happening under some unusual setups.  It happened to me running on a mac.  I got around it by installing the dbus server, but some people may not want to do that.
=> Do not crash when dbus server is unavailable, just emit an error message

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Addressing the longstanding <kbd>Ctrl+scroll</kbd> zoom in/out issue, as expressed in these old requests
- https://bugs.launchpad.net/terminator/+bug/1505292
- https://bugs.launchpad.net/terminator/+bug/1638607
Some laptop users (including myself) often bump the trackpad while holding <kbd>Ctrl</kbd>, which results in the terminal drastically zooming in and out (it's super sensitive).
The usual fix to get around this was to press <kbd>Ctrl+0</kbd> to reset the zoom everytime it happened, but this often fails to restore the original symmetry among split windows in apps like `vim` and `tmux`.
Needless to say, it's also annoying having to reset zoom scale so often.
- Adds a checkbox to the `Profiles > General` section of terminator preferences
- If checked, don't run the …
=> Added option to disable ctrl+mousewheel zoom

terminatorlib/cwd.py, terminatorlib/terminal.py, terminatorlib/terminator.py
This came from a comment in gitter where @FernandoBasso noticed that the cwd wasn't being set properly if the vte shell functions weren't installed.
=> fix cwd for non-vte shells

terminatorlib/terminator.py
I'm probably the only person who uses terminator with the Quartz backend (on a mac) and does not even have the X11 libs installed, but I think we'll run into this more and more often as X11 gets phased out and wayland is used more often
=> Fix crash when GdkX11 module is not available when creating layout

terminator
for #78 
Well, this was an adventure.  It turns out that it wasn't the environment variable that changed, but actually the internals of the python psutil module, which meant that we weren't actually detecting whether or not ibus was running, and consequently never setting the proper ibus environment variable.
=> fix detection of whether or not ibus is running

terminatorlib/debugserver.py
A weird difference between python 2 and 3, I believe.  Without this when you try and run the debug server it will not be able to read or write to the socket the debugserver creates.
=> fix io errors on debugserver

doc/terminator.1, terminatorlib/optionparse.py
This PR fixes #125 
@mattrose let me know if this works, I also modified the doc section.
=> Adding maximize option

terminatorlib/terminal_popup_menu.py
So, back in #64 nbeaver added a "Layouts" popup menu item.  I liked it, and I did pull it in, but in reviewing that, I thought of a better way, which was to just popup a submenu with a list of layouts, rather than a separate window.  This PR implements that.
=> launch new layouts directly from right-click menu

terminatorlib/config.py, terminatorlib/terminal.py
This is a WIP right now.  I'm going to wire up the preferences dialog next.  If you want to try this out, you can add a `line_height` entry to a profile in `~/.config/terminator/config`
=> add line_height config variable

terminatorlib/prefseditor.py
This PR should fix #149. 
The idea is to check whether a key value will change if a Shift key is down (see [level](https://developer.gnome.org/pygtk/stable/class-gdkkeymap.html)). If it will, then remove the Shift modifier from `mods`. 
One exception: if a key binding contains a letter then the Shift modifier is not removed. This is because, for some reason, a key value of a letter is never modified by the Shift modifier and always corresponds to a key value of a lowercase character. This is already handled in `terminatorlib/keybindings.py`. 
I'm new to GTK, so not quite sure how to emulate signals with PyTest. I tested the following key bindings (manually) to make sure it works: 
- `Ctrl + Shift + 1` translates to `Ctrl + !`
- `Ctrl + A` translates to `Ctrl + A`
- `Ctrl + Shift + A` …
=> Fix: Allow Key Bindings with Shift-Modified Keys

terminatorlib/preferences.glade, terminatorlib/prefseditor.py
This pull request allows live previewing of profile color changes. Specifically, the foreground, background, and palette colors, when changed, will be shown immediately in the terminator window. Prior to this pull request, the preferences would need to be saved before changes were shown in the window. This allows a more intuitive experience of changing colors.
=> Allow live previewing of profile color changes

terminatorlib/paned.py
testing a fix for #68 Basically spit out a debug message that says it can't find the uuid of the terminal it was trying to close.
=> fix traceback on paned.py

terminatorlib/terminator.py
=> remove unused gnome session code

terminatorlib/paned.py
to allow you to paste from the first column to the right of a vertically split window.  Fixes #191
=> Add 'wide_handle' property 

terminatorlib/config.py, terminatorlib/prefseditor.py, terminatorlib/terminal.py
This behaves exactly as the "New Group" titlebar menu option.  It will move the focus to the randomly selected group name, and let you edit it, and then returns focus.
It's currently disabled, but settable in the preferences.
=> Key binding option for creating group in current terminal

terminatorlib/terminal.py
So there was something I noticed while working on #202 where the "login shell" option in preferences was just wrong.  When that option was enabled, rather than sending the "-l" option to the shell, indicating you wanted a login shell, it would send: -$SHELL ($SHELL being whatever your shell was set to, so -/bin/bash or -/bin/zsh)  This does not do what the option says it does, see 
```
Terminal::spawn_child: Forking shell: "/bin/bash" with args: ['-/bin/bash', '-c', 'foo']
```
=> fix login_shell option so that it sends -l rather than -shell

terminatorlib/prefseditor.py, tests/test_prefseditor_keybindings.py
This PR should fix #190.
**Changes:**
It's no longer possible to assign the same key binding to more than one action. For example, now when reproducing the steps in #190, the following error message will be displayed:
**Tests:**
I added `tests/test_prefseditor_keybindings.py` which tests that
1. Default key binding accelerators are distinct.
2. Message dialog appears when a duplicate key binding accelerator is attempted to be assigned to a different action.
3. Duplicate key binding accelerator cannot refer to more than one action.
One thing to keep in mind when running the tests locally is that the key bindings redefined in `~/.config/terminator/config` can conflict with the tests. That being said, the simplest way to avoid any possible conflicts is to remove …
=> Fix: Forbid Duplicate Key Bindings in `Preferences > Keybindings`

terminatorlib/prefseditor.py, tests/test_prefseditor_keybindings.py
PR #150 introduced a bug which made it impossible to add the `Shift+Tab` key binding in `Preferences>Keybindings`. This PR should fix this. 
The commit messages in this PR have a more detailed explanation about the nature of the bug. 
I also added automated tests to check that editing a key binding in `Preferences>Keybindings` with the predefined key combinations, including `Shift+Tab`, produce the expected accelerator.
=> Fix: Allow `Shift+Tab` Key Binding

terminatorlib/terminal.py
2 reasons for this:
1.  spawn_sync is being deprecated.
2.  spawn_async API has a callback and other goodies that we can leverage in the future.
=> update Terminal.spawn_child() to use spawn_async, not spawn_sync

terminatorlib/plugins/command_notify.py
So, as per usual, this has a bunch of caveats.  It only works on Redhat-ish systems, as they're the ones who have integrated [this patch](https://bug711059.bugzilla-attachments.gnome.org/attachment.cgi?id=371905).  Cross-platform support for notification on prompt is bogged down in https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/13 so this is the best I can do until we can get VTE to agree on some kind of signal to the UI when a command is complete.
fixes #11 kinda
=> Command notify

terminatorlib/terminal.py
This reverts commit f5cbdce5fce1522007c9f4937e06a8a4e9486a51, reversing
changes made to e1476a2ef23def50f3a7ca70ce639e50b8f94346.
VTE.Terminal.spawn_async is not ready for prime time yet, apparently
=> Revert "Merge pull request #208 from mattrose/update-vte-spawn"

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
fixes #5 
This is a very barebones implementation so far, and doesn't even have GUI controls yet.  (Have I mentioned how much I hate Glade?) but...
Witth this code, in your profile, you can now set `background_image = $image_file` and it will set the background of the terminal image to the image.  This is the background for each pane, so the image will no span multiple panes, but instead will repeat (I think I can configure that if it's a popular feature request, but I don't want to get too ahead of myself)
You can also set `background_alpha = x` where x is a float between 0 and 1 (eg: 0.55) which will blend in the background color from your theme to aid readability.
I have to say, I was a huge skeptic on the usability of this, it just seemed like a popular feature and people did come up …
=> Background image

terminatorlib/config.py
This PR changes how the config file is saved.
Current behavior:
1. write parser contents to config.tmp
2. rename config.tmp to config
Proposed behavior:
1. copy config to config~
2. write parser contents to config
3. remove config~ (this could be optional)
Fixes #234
=> Change how config file is saved

terminatorlib/prefseditor.py, tests/test_prefseditor_keybindings.py
This PR should fix incorrect clearing of key bindings in `Preferences > Keybindings`, which was introduced in #196.
**Steps to Reproduce:**
1. Open `Preferences > Keybindings`.
2. Clear any non-empty key binding, that is double click on any key binding which doesn't say `Disabled` and then press Backspace.
3. Try to assign a new key binding to any action - it won't work.
This happens because `Gtk.accelerator_parse`, which was used in #196, doesn't allow `None` to be used as a value. To fix this, the key binding value is now set to an empty string (`""`)  instead of `None` the moment it's been cleared.
I also added a test to reproduce the behaviour described in this PR.
=> Fix: Key Binding Clearing in `Preferences > Keybindings`

terminatorlib/paned.py
There was a tiny section of the divider between two panes laid out one on top of the other that was transparent.  This fixes it for some reason
=> fix the handle on the divider between horizontal panes

terminatorlib/config.py, terminatorlib/searchbar.py
- Add a configuration option named 'case_sensitive' to determine whether the searchbar matches case by default
- Persists this state to the config file whenever it is changed so that it retained whenever terminator is relaunched
=> Preserve searchbar case sensitivity state in config file on state change

terminatorlib/terminal.py
=> remove workaround for https://github.com/ibus/ibus/issues/1802

terminatorlib/config.py, terminatorlib/searchbar.py
This change adds support for inverting the search direction - searching will optionally be from the bottom-up (meaning, recent terminal history will be matched first). 
Selected search direction is persisted in the config file so that it is retained the next time terminator is launched.
=> Add support for inverted search

terminatorlib/terminal.py
=> fix drag and drop issues on KDE

terminatorlib/plugins/custom_commands.py, terminatorlib/terminal.py
feed_child_binary was a weird workaround in the VTE lib[1] it is now fixed and feed_child_binary is deprecated[2]
The downside of this is that feed_child now only accepts UTF-8 encoded strings.
I'm going to try this for now but may have to revert and lobby for feed_child_binary to come back, but we'll see how this goes.
[1] https://gitlab.gnome.org/GNOME/vte/-/issues/201
[2] https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html#Vte.Terminal.feed_child_binary
=> replace feed_child_binary() calls with feed_child()

terminatorlib/terminal.py
This PR implements a different method for dimming terminals when the focus left them.  We used to manually go through each color in the user's settings and set them a little bit darker.  This works for 16 colors and 256 colors, but the vte people want to change this.  I've moved it so that we just paint a semi-transparent layer of the background color over the entire terminal and this approach actually simplifies the code quite a bit.
=> fix issue #74

terminatorlib/terminal.py
The background overpainting stuff uses Vte.Terminal.get_color_background_for_draw() to get the background color, but this doesn't exist on versions prior to 0.60, if it doesn't exist, fallback to reading the background color from the config.  I think It's a bit slower, but it works.
fixes #292
=> fix issue with older vte lib

terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py, terminatorlib/terminator.py
=> fix background image profile preferences ui

terminatorlib/config.py, terminatorlib/util.py
This makes us follow the XDG spec better.  If a user configuration doesn't exist in ~/.config/terminator/config look through the paths in the environment variable $XDG_CONFIG_DIRS and /etc/xdg [1]
fixes #308 
[1] https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
=> load config from XDG_CONFIG_DIRS if user config file doesn't exist

doc/terminator_config.5, terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
=> remove rewrap on resize from option and remove functions too

terminatorlib/terminal.py, terminatorlib/terminal_popup_menu.py, terminatorlib/titlebar.py
This is a forward port of a feature I added to a local 0.97 copy a number of years ago after switching away from Gnome Terminal.  This approach was what I figured out first, so it may not be the best way to implement the feature (the relaunch option in the right-click menu, for example), so I'm just putting this out there and wouldn't be surprised if it needs further development before merging.
I don't recall for sure, but Terminal.relaunch_command might have been needed for some use case I've now forgotten the details to.   I've not tried re-testing without it.
=> Feature: Relaunch command option on held open after child exit

terminatorlib/terminal_popup_menu.py
apparently Gtk.Menu.popup() was deprecated in 3.22 and doesn't work on wayland and sway
=> update to non-deprecated Gtk.Menu popup call

terminatorlib/layoutlauncher.glade, terminatorlib/layoutlauncher.py
I am not sure, but directly setting the size on Python fixed the issue in my platform.
I am also increasing the height +50 pixels because a rectangular size seems more fit than a square box.
=> Fix #345 The Alt+L layout chooser is too small

remotinator, terminatorlib/ipc.py
Permit to switch profile via `remotinator` as mentioned at #321 
```sh
remotinator switch_command --profile [name]
```
=> Remotinator "switch_profile" command

terminatorlib/terminal.py
I found a race condition where the command I specified for the new vte had already exited by the time `grab_focus` was called. This caused the terminal to start cleaning up and the `self.vte` was `None` by the time `grab_focus` executed.
This caused a `Could not call method 'has_focus()' on NoneType` error. Not a huge deal because the terminal closed itself anyway. Easy fix to avoid the error by adding the None check before the `has_focus` call.
=> Fixed race condition when calling grab_focus after underlying vte could be closed

po/pt_BR.po
I know translations are supposed to be on transifex but this is just a drive-by fix for issues I found when using terminator, I don't plan to work on translations in the long term.
=> i18n: pt_BR: add missing space in translations with shortcuts

terminatorlib/terminal.py, terminatorlib/window.py
I tried to use Window geometry hints, but it didn't work.
I tested this on: Debian 11 (all updates), Debian 10 and Ubuntu 20.04.
Details:
it seems that "set_geometry_hints" wants "None" as first argument.
Also, it's necessary to disable geometry hints, if we want to avoid restarting terminator.
So I wrote a little function that does that.
=> Fixed geometry hints

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Instead of Ctrl-left click.
Note: I only have glade 3.22.2 instead of the 3.36.0 used for the previous setup.
I guess that's why there have been some editions in the XML, apart for the new checkbox.
I have absolutely no idea if that's a problem or not… the window works well on my Ubuntu 20.04, at least.
=> add feat: config to open links with single click

remotinator, terminatorlib/ipc.py
I found `has_focus` wasn't working but `self.terminator.last_focused_term.uuid.urn` seems to be working. I also updated remotinator to support new `get_focused_terminal` ipc command.
=> Added new get_focused_terminal dbus command which returns uuid of current focused terminal

remotinator, terminatorlib/ipc.py, terminatorlib/terminal.py
This includes get_focused_terminal pull request too (which was separately functional) to add new `vsplit_cmd` and `hsplit_cmd` dbus ipc commands.
Now we can get the focused_terminal and then split it and run a command all over dbus. Here is the python that could call the new `hsplit_cmd`
```
focused_terminal_uuid = ipc.get_focused_terminal(None)
ipc.hsplit_cmd(focused_terminal_uuid, 'iftop', 'sudo /sbin/iftop -i eth0', None)
```
Then we see terminator now spawns and names the new horizontal split appropriately
=> Add new vsplit hsplit cmd dbus

terminatorlib/plugins/run_cmd_on_match.py, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Adds the necessary features to add a regexp/command plugin.
My use-case is to be able to open a file at a specific line in my IDE, just by clicking on an error message.
For instance, for opening a python script indicated in a python error, within vim, use the following configuration with the RunCmdOnMatch plugin implemented in this PR:
- regexp = `\B(/\S+?\.py)\S{2}\sline\s(\d+)`
- command = `gvim --servername IDE --remote +{1} {0}`
This adds three interconnected features: 
- a plugin which can run any command when clicking on a link inserted on texts matching a regexp,
- a way to hide plugins in the preference/plugins window (by prefixing their name with an underscore),
- a way to bypass the URL handler (xdg-open), when the URLhandler plugin returns a `terminator://` URL.
The overall …
=> Feat+run cmd on match

terminatorlib/terminal.py
The typo was introduced in 5fb74661287503abfbd9e2c8e62c58ee6b99cbbc.
=> Fix the background image loading exception handling

terminatorlib/paned.py
Since the bug is well explained in the issue, let's talk about the patch.
I studied this problem for a few hours.
Apparently, this bug *always* occurs when there are two terminals (horizontal or vertical, doesn't matter).
It also occurs when there are more than two, but I didn't figure out any logical pattern.
Basically, while loading a layout, the function `set_position_by_ratio` indirectly calls `new_size` (through Gtk.main_iteration()) which calls `self.set_position(self.get_position())`.
Only after set_position is executed the position is actually set (inside `set_position_by_ratio`), based on the ratio.
But the problem is that set_position takes self.get_position() as argument, while it still hasn't been set. So it calculates the new ratio, which is always about 0.5.
Initially, I …
=> Fixed issue #433 (layout sometimes ignores ratio)

terminatorlib/preferences.glade, terminatorlib/prefseditor.py
The checkbox for "Clear selection on copy" was always unchecked, because the widget active status was not set.
And the id of the checkbox in preferences.glade was not set.
Try to check "Clear selection on copy" and then close the preferences menu. When opened again, it's unchecked.
=> Bug Fix: 'Clear selection on copy' is always unchecked

terminatorlib/window.py
The function `on_hide_window` is called even if the window was destroyed.
On line 135 we bind that function using `Keybinder.bind(...)`, but never "unbind" it. Now, since all the terminator windows are run by one python process, this key binding remains until all windows are closed. So what happens is that when the key combination for hide_window is typed, `on_hide_window` is called even if the window was destroyed.
The first thing I tried to do was to unbind it, but this caused all the windows to lose the binding, so that hide_window would not work anymore at all.
Simply store in a variable `isDestroyed` the value True when the window is destroyed, and do nothing if `on_hide_window` is called.
=> Fixed Issue #425 (hide_window will try to show a destroyed window)

terminatorlib/notebook.py
Resolves [#issue400](https://github.com/gnome-terminator/terminator/issues/400)
Apparently, we do not need to subscribe on focus-grub event and put the grab back to the VTE terminal. Adding a setting can_focus=false is enough.
Applying it I am still able to rename the tab by a double click, though just clicking on it does not steal l the focus.
=> Set CAN_FOCUS to False for notebook widgets

remotinator, terminatorlib/ipc.py
=> add switch_profile_all command to remotinator

remotinator, terminatorlib/ipc.py
This is to add parameters to the remotinator vsplit and hsplit command.  You can now run `*split -T <title> -x <command>` and it will split the termnal and run a command in the new terminal
=> add parameters to remotinator split commands

terminatorlib/preferences.glade
This is a small change to the preferences.glade file.
After the last PR (#481) I've noticed some of the checkboxes "blink".
Basically, in the glade file, they are "on", but when terminator reads the config file, they are set off. So there is this very small time span where they are on, and suddenly turn off, causing some sort of blinking.
I think the reasons because this did not happen before, is that the GUI was bigger and there was more stuff to load, so there was enought time to read and set all the settings.
So I set all checkboxes to false by default, so that they turn on only when Terminator reads the config. I also removed some empty rows/columns from that file.
=> GUI: set all CheckButtons off to avoid blinking + remove grid empty rows/columns

terminatorlib/ipc.py, terminatorlib/prefseditor.py
fixes #401 
Also cleans up the preferences window when a json layout or profile is called and doesn't expose the internal json parameters.
Also cleans up a print statement from a while ago when I was working on background images.
=> fixes for --config-json

terminatorlib/notebook.py, terminatorlib/window.py
Fixes #302
Note - This pull request is to show the progress. I have done very little testing, so I don't recommend pulling it right now.
As said in the issue comments, `set_tab_detachable` does the job. The [code](https://stackoverflow.com/a/56377756) found on StackOverflow gave me a guideline, but much of that stuff is already implemented somewhere in Terminator. So I had to create only one function, `create_window_detach`.
About `self.hoover`: without calling that function, if a tab is detached and a notebook only has 2 tabs, the resulting notebook only has 1 tab, causing some troubles.
Most of the work was about reading the documentation.
---
I'll finish testing soon, and maybe fix that Drag-and-drop problem that we were talking about in the comments, since it's related.
=> Make tabs detachable + minor bugfix

terminatorlib/terminal.py
Fixes a problem that we discovered in #498, but not the entire issue.
For some reason, something related to debug makes Terminator crash. That might be another bug.
Apparently, the parameter order was messed up, and the `Restart the command` thing would work only when there is a custom command. With this patch it should work fine even if it's not selected.
=> BugFix: terminal won't restart if there is no custom command

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py
Very simple changes, but such a big time saver.
Currently, if you want to duplicate a profile, you either do it in the config file, or you have to add a new profile and manually set all of the settings again.
Also as a note, I think the `Disable Ctrl+mousewheel zoom` button in Profiles is broken. It sometimes does not change value when switching between profiles.
=> Add a "Copy" button to clone profiles

terminatorlib/window.py
Fixes #509
The shift key gets ignored by the global Keybinder. That's not a bug in the library, it's a misconfiguration.
By default, keybinder uses "cooked accelerators".
I quote from the issue comments.
> The best documentation I found is the comments in the code. They are pretty good.
>From [this](https://github.com/kupferlauncher/keybinder/blob/master/libkeybinder/bind.c):
> > "Cooked" accelerators use symbols produced by using modifiers such as shift or altgr, for example if "!" is produced by "Shift+1".
There is this C function
```c
keybinder_set_use_cooked_accelerators
```
So yeah, we just had to disable them using this:
```py
Keybinder.set_use_cooked_accelerators(False)
```
---
There is another issue about hide_window not working (#427). I doubt it's related to this, I think that …
=> Bug Fix: hide_window keybinding ignores Shift key

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Fixes #415
These changes add the `disable_mouse_paste` setting. Default is `False`. When enabled, middle mouse click (or if putty, right click) will do nothing.
The setting is global, because it affects broadcast.
=> Add 'Disable mouse paste'

terminatorlib/preferences.glade
Fixes a bug in Preferences, Keybindings.
Right now, to activate the search bar, we need to click the tree menu.
This change makes the search bar work without having to click the widget, giving the focus to it automatically.
=> Automatically focus the Keybindings menu

doc/terminator_config.5, terminatorlib/config.py, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Unbound by default, pastes primary selection.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
=> Add paste_selection keybinding.

terminatorlib/plugins/custom_commands.py
Custom Commands plugin was able to save only one-line commands. This enables to save and execute commands with multiple lines.
=> Allow multiline commands in Custom Commands plugin

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py
Partially addresses #518 , not sure where I can insert a config to modify color of terminal seperator so I'll put that one on hold for now.
1. Make it such that if handle_size is out of range, handle_size will be defaulted to smallest.
2. Terminator seperator size in gui settings will have range from 1 to 20, instead of -1 to 20 which is extremely misleading as -1 and 0 is out of range and previously defaults to a larger value.
=> Fix terminal separator size setting

terminatorlib/util.py
There is no LANGUAGE available on environ of centos, so there is no way to select a new LANGUAGE, even though only English is available.
=> os.environ does not have LANGUAGE in Centos8.

terminatorlib/prefseditor.py, terminatorlib/window.py
Fixes #548 
As explained in the issue, if a keybinding's value is set to None, it becomes impossible to remap it.
However, I've noticed this affects all the keybindings: if one of them is set to None, then the Preferences Editor won't be able to change any value.
This is because function `Gtk.accelerator_parse` (which is called to avoid keybinding duplication) does not allow None as a value.
Also, since we should consider `None` as a valid value for `hide_window`, we have to check for both `''` and `None` (last changed in #515)
=> Fix: 'None' value for keybindings breaks editor

terminatorlib/config.py, terminatorlib/terminal.py
Plus, fixed code duplication and organized code.
The problem: even if the `background_type` is not `image`, terminator will still print an error saying that the file was not found (when the file was deleted). To fix this, you should go to the config file and manually delete the `background_image` entry.
Solution: check if `background_type` == `image` before attempting to read the image file.
I also removed the duplicated code, that was identical to set_background_image.
In background_draw (which by the way seems to have bad performance) becomes unnecessary to check for `background_type`.
=> Improve and optimize the code for background images

terminatorlib/notebook.py, terminatorlib/terminal.py, terminatorlib/window.py
Fixes #550
These changes make a zoomed/maximized terminal unzoom on interactions such as: creating a new tab, resizing the terminal, splitting it etc...
There are still problems with two of these interactions: rotating the terminal and moving to another terminal.
The function `get_allocation()` returns `(width: 1, height: 1, ...)` right after an unzoom.
The bug can be replicated with a few terminals (I use one on the left, one top-right, one bottom-right). Zoom the bottom-right one and try to rotate or move to the top-right terminal.
What I get for the rotation is that one terminal is big, the other two are very small.
=> Unzoom terminal on interaction

terminator
Using this hotfix for a while, did not observe any discrepancy. Creating this PR in order to
permanently(hopefully) fix the issue without any local modification.
=> Added hotfix for #78 that deletes GTK_IM_MODULE environment variable

terminatorlib/borg.py, terminatorlib/config.py, terminatorlib/container.py, terminatorlib/factory.py, terminatorlib/notebook.py, terminatorlib/optionparse.py, terminatorlib/paned.py, terminatorlib/plugin.py, terminatorlib/prefseditor.py, terminatorlib/terminal.py, terminatorlib/terminator.py, terminatorlib/titlebar.py, terminatorlib/window.py
In the code, we can find code like this:
```python
dbg('ConfigBase::get_item: %s found in globals: %s' %
(key, self.global_config[key]))
```
But this gets printed:
```
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
```
There is a repetition, because the `dbg` function already adds the name of the function at the beginning (4d216633fca8ca46fc3b51fdf2b382db93e3ade1).
The same should probably have been done to the `err` function.
This change should make the debug logs easier to read.
=> Remove duplicated info in some debug messages

terminatorlib/terminal.py, terminatorlib/util.py
This is adding experimental flatpak support as well as definition.
It builds and works ok however flatpak-spawn doesn't seem to be handling tty properly (see https://github.com/flatpak/flatpak/issues/3697)
It's usable and perhaps could be submitted to flathub beta and wait until flatpak-spawn resolves issues with tty or someone rewrites it. 
Fixes: https://github.com/gnome-terminator/terminator/issues/206
=> Add initial flatpak-spawn support

terminatorlib/prefseditor.py
While editing the preferences in terminator, If you select a particular palette, all of the palette widgets get locked which prevent you to make small changes according to your taste in that particular palette. To do that, you need to select "custom" palette where the widgets get unlocked and you can change the palette. I have changed it so that you can make slight changes then and there and don't have to select "custom" and change it from there. This is more convenient and easier to understand (I was stuck trying to make slight change to the "solarized" palette for a very long time).
=> Modification in the /terminatorlib/prefseditor.py file

README.md, terminatorlib/prefseditor.py
in #590 @amaan211 fixed it so that you could edit the palette colors for the themes without selecting "custom" first.  This allows the same change for the foreground and background colors.
=> More fixes to the Color pickers in the Preferences Editor

terminatorlib/container.py, terminatorlib/plugins/save_last_session_layout.py, terminatorlib/terminal.py, terminatorlib/terminator.py
- added plugin save_last_session_layout.py
- saves the working directory and layout of last session (last window) closed
- layout is saved under name of SaveLastSessionLayout
- can be loaded from context menu (right click) -> layouts -> "SaveLastSessionLayout"
- last working directory is also saved
=> Plugin Submission : SaveLastSessionLayout Uses Layout to Auto-Save Last session and CWD

INSTALL.md
It greatly improves readability and helps to avoid scrolling.
Now this badge looks like this:
[![Packaging status](https://repology.org/badge/vertical-allrepos/terminator.svg?columns=3)](https://repology.org/project/terminator/versions)
=> docs: Change number of columns in repology badge

terminator
By default, GTK sets the prgname to argv[0], which is then used to choose the correct .desktop file. If the program is run through a symlink, such as through `/etc/alternatives/x-terminal-emulator`, argv[0] is not `terminator` so under Wayland the desktop file is not detected, leading to a missing icon.
Possibly fixes these issues:
https://askubuntu.com/questions/1218884/terminator-does-not-add-to-dock-icon-when-opened-via-ctrlaltt
https://bugs.launchpad.net/terminator/+bug/1726525
=> Fix missing icons when started with Ctrl-Alt-T

terminatorlib/optionparse.py
--execute behaves now like in the docs:
Runs  the rest of the command line instead of your default shell
or profile specified command.
This fixes it's proper usage with tools like gio or xdg-open
#660
=> Fix argument handling of the --execute flag

terminator, terminatorlib/terminator.py
I am sick of ibus breaking every single time we issue a new release, so as of now, I've gone through the code and removed all of the workarounds that we have put in to try and get around issues in ibus, and GTK Input Methods in general.
The code as it stands should work, I'm going to mention a bunch of people in this PR and ask them to beta test this change.
=> Remove all ibus workarounds

terminatorlib/preferences.glade, terminatorlib/prefseditor.py, tests/test_prefseditor_keybindings.py
- added a filter to the preferences menu for easy access to shortcuts
- may require some tweak, on search term size and update
Note: when edited in prefs it seems the Short Cut Labels in (right click) Context Menu are not updated will fix that in that bug Issue #662
=> [bug 559] Add menu autocomplete #559

terminatorlib/container.py, terminatorlib/notebook.py, terminatorlib/paned.py, terminatorlib/window.py
When there are multiple tabs, the notebook top bar is visible.
Now, it is possible to split the terminal and then zoom/maximize, so that the top bar is hidden.
But when there is only one terminal in the notebook tab, it's not possible to do it.
I added the signals for the notebook, so that it does zoom/maximize now.
When unzooming a tab **with a single terminal** in it, the tab is moved to the end of the notebook.
I currently have no idea why it does that, but since it can be annoying I think it's best to fix it before merging.
The function I deleted in the second commit (container.py) seems to be unused. Nowhere it's called and other functions do the same thing.
=> Zoom on notebook even if there is only one terminal in the tab + keep tab position and label in notebook rotation

terminatorlib/prefseditor.py, terminatorlib/terminal.py
Use the term 'zero padded' instead of 'padded' in prefs key binding and terminal pop up menu, to be consistent with the doc.
https://gnome-terminator.readthedocs.io/en/latest/gettingstarted.html?highlight=padded
Beside it will be consistent with the docco, it also took me a while to understand what 'padded' mean, specially as long as you don't open more then 10 terminals where it looks like the same as non padded.
OTOH  I still don't understand what is hte use case of terminal id is for so may be this is not important.
=> Use the term 'zero padded' instead of 'padded'.

data/terminator.appdata.xml.in
This MR is part of an [initiative](https://gitlab.gnome.org/GNOME/Initiatives/-/issues/35) to fade out legacy app branding. Following the [Software Policy](https://wiki.gnome.org/Foundation/SoftwarePolicy), GNOME branding is reserved for official GNOME software (Core apps and Development tools.) You can find a summary in [this blog post](https://blogs.gnome.org/sophieh/2022/06/08/apps-attempt-of-a-status-report/).
If you think that your app is a special case that needs an exception from the software policy, we would ask you to leave a comment about your app's case in GNOME/Initiatives#35.
/label ~"9. Initiative: Legacy app branding"
=> data: Remove GNOME branding

terminatorlib/config.py, terminatorlib/prefseditor.py, terminatorlib/terminal.py
- implemented the short-cut
- seems the key combo is already taken 'go_prev' : 'p'
- How about : 'k', I will make the change for now.
- But adding key seq to a long list of keypress function breaks my heart, If the plugin util keybind makes it to the main branch, I will take this out and may be have a shortcut plugin to handle these.
- Also selecting of Keybindings page is being done for this specific case Page = 3
- A notebook tab number and title map would remove this. Which can be configurable, later.
=> [bug 680] Open up keybindings page on keypress #680

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Closes #644.
After quite some time, I made the GUI changes that were necessary. This PR adds different drawing modes and alignment for the background image.
***
New config options: `background_image_mode`, `background_image_align_horiz` and `background_image_align_vert`.
1. `background_image_mode`:
- stretch_and_fill
- scale_and_fit
- scale_and_crop
- tiling
2. `background_image_align_horiz`:
- left
- center
- right
3. `background_image_align_vert`:
- top
- middle
- bottom
The defaults are `stretch_and_fill`, `center` and `center`. This is the behavior that terminator has right now with images.
=> Background image drawing modes and alignment

terminatorlib/terminal.py, terminatorlib/terminator.py, terminatorlib/titlebar.py
When pressing Ctrl+Click on the group button at the top of a terminal, if both the current terminal and the target terminal are not assigned a group:
- Before this change, nothing would happen.
- After this change, a new group with a randomized name will be created, without prompting the user for the group name.
Suggestion made at issue #685, with the goal of improving ergonomics.
Demonstration:
=> Ctrl+Click on group button automatically creates groups whenever needed

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py, terminatorlib/terminal.py
Hello!
I normally don't use title bar, thus differentiation between active and inactive windows, when there is not much in the foreground, is hard for me.
To better explain this, check out this GIF - the problem:
When there is not much data on the terminals, then it's hard to distinguish in which terminal I'm currently writing.
With this PR, one can change the background brightness of the Inactive window:
I have introduced a setting which allows changing the background brightness of the inactive window:
This PR introduces changes to the background color, and the implementation is a simple copy-pasted solution, scrapped from the `inactive_color_offset`, which controls the brightness of the font for an inactive window.
At this stage, it is a draft, because I have few questions:
1. Do you …
=> Better distinguishing of inactive windows from the active one, by changing the background brightness

terminatorlib/terminal_popup_menu.py
When the keybinding for an action that also appears in the context menu is None, python can't do it's usual string tricks and throws a backtrace, and doesn't display the menu.
Fixes #724
=> Fix context menu keybinding reading.

terminatorlib/terminator.py
set_focus() should do the trick according to the docs, so let's just use that, and not go to extraordinary measures.
fixes #714 hopefully
=> Remove hack to ensure that focus is set.

terminatorlib/terminator.py
This caused all the new windows to be unfocused, forcing the user to manually focus one.
From the [docs](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Window.html#Gtk.Window.set_focus):
> If `focus` is `None`, unsets the focus widget for this window.
On my machine, the last_active_window feature seems to be broken.
I've spent some time trying to figure out why, but found nothing.
Most of the `layout_done` function appears to do nothing useful, but that might be different on other Desktop Environments.
It's an old problem, with commits from 10 years ago trying to fix it. And it's a mess.
=> Do not remove focus from the last_active_window

doc/terminator.1, doc/terminator.adoc
`terminator.1` is the man page that opens after typing `man terminator`.
It currently contains a few problems, such as a missing newline, options and their arguments being all in bold instead of bold and italic, keybindings out of place or in the wrong sub-section...
All of that should now be fixed.
The AsciiDoc format seems to me way more friendly than the manpage one.
To generate the manpage file, we just need to run `asciidoctor -b manpage terminator.adoc` after modifying the source.
Maybe it would be a good idea to add a script that runs that command.
***
I've started working on a manpage for remotinator as well. And ideally, `terminator_config` should be rewritten too, but that requires way more work and updates.
=> Rewrite terminator.1 man page in AsciiDoc format

po/fr.po
=> fix: typo in french translation

doc/gen_manpages.sh, doc/terminator_config.5, doc/terminator_config.adoc
This took some time, but it's here!
In a previous PR (#733) I rewrote `terminator.1` in AsciiDoc. Now I've done the same for `terminator_config.5`.
The information in `terminator_config.5` was severely outdated and most of settings added through the years were missing.
I've also added a small script, `gen_manpages.sh`, that should be used to generate the manpages after changing the `.adoc` files.
=> Rewrite terminator_config.5 man page in AsciiDoc format

terminatorlib/config.py, terminatorlib/notebook.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py
Fixes #697.
Not sure why so much markup got changed, guess some new glade version thing.
=> Add detachable tabs feature to preferences

terminatorlib/plugins/logger.py
In vte 0.72 there was a regression that caused Vte.Terminal.get_text_range() to fail to return the text requested However, in the same version, there was a new call introduced that does retrieve the text, so if I detect a vte minor version above 72, I call that instead.
Fixes #776
=> Alter get_text_range call based on VTE version

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py
This reverts commit c8cd50ba9a7c1b4ecac83c2336122d4133cfabe2.
This commit oddly rendering saved layouts.  I decided to revert it after not finding an easy way to achieve both.
Fixes #766
=> Revert "modify terminator separater size setting in gui to start from 1"

terminatorlib/plugin.py, terminatorlib/terminal.py
Ref: https://github.com/gnome-terminator/terminator/issues/808
Some plugins using KeyBindUtil https://github.com/gnome-terminator/terminator/issues/805 don't receive Key events in newly opened window / terminal. Reloading of plugins helps and gives plugins an option to reconnect terminal events. This patch given on way or opens up a discussion on this and to test this, may be a better solution exists.
DEPENDENCY
Examples:
https://github.com/gnome-terminator/terminator/issues/706
https://github.com/gnome-terminator/terminator/pull/682
=> [bug 808] Plugins-dont-receive-keboard-signals-on-newly-opened-windows

terminatorlib/terminator.py
The "Insert terminal name" Plugin causes the following traceback Traceback (most recent call last):
File "/Users/mattrose/Code/terminator/terminatorlib/terminator.py", line 588, in do_insert_term_name
term.feed(name)
File "/Users/mattrose/Code/terminator/terminatorlib/terminal.py", line 1709, in feed
self.vte.feed_child(text)
This PR fixes it so the plugin inserts the terminal name, as intended.
=> Fix Insert Term Name Plugin error

doc/terminator.1, doc/terminator.adoc, terminator, terminatorlib/ipc.py, terminatorlib/optionparse.py, terminatorlib/window.py
Useful for Wayland where global shortcuts are not available. Use window manager to bind "terminator --toggle-visibilty" to a keyboard shortcut.
Related bug: https://github.com/gnome-terminator/terminator/issues/427
=> Add command line option --toggle-visibility

terminatorlib/terminal.py
The actual sixel related change is very small. It should be safe and (I hope) uncontroversial.
The flake.nix I used to dev/test this is also included. It enables one to (relatively) easily install a modified instance of VTE compiled with SIXEL support included. If it's unwanted, I don't mind dropping it from the pull request. I'm sorta new to Nix so I doubt it's perfect.
=> Enable sixel support in VTE if it's available.

terminatorlib/config.py, terminatorlib/preferences.glade, terminatorlib/prefseditor.py
**Changes** 
- added basic config restore option from preferences window
- changes to glade made in addition to addition of destory signal
- minor cleaup in config to have a single function return confilg filename via get_config_filename
**Things to Cross Check**
- position of restore button in preference window
- name of button
- additional behavior like enabling button only on change or a simple standard way like current one is ok ?
=>  [bug 802] - Ability to undo or restore changes to the preferences #802

terminator
Commit 2e1dd1f breaks --new-tab and --toggle-visibilty.
On each call a new window is created, from else on line 122.
Introduced if cut the last else from the two first if causing last else to be called every time.
=> Fix: Add CLI command to reload configuration

doc/terminator_config.5, doc/terminator_config.adoc, terminatorlib/config.py, terminatorlib/container.py, terminatorlib/notebook.py, terminatorlib/window.py
(Partially?) solves #830
This is apparently a very requested feature. This PR makes it possible for the "Close?" confirmation dialog to appear even if there is only one terminal.
The `suppress_multiple_term_dialog` setting has been replaced with `ask_before_closing`, which can have values '_never_', '_multiple_terminals_' and '_always_'.
'_multiple_terminals_' is the default, so that Terminator's default behavior remains the same. The "Do not show this message next time" checkbox sets `ask_before_closing` to '_never_', regardless of its previous value.
The confirm close dialog is the same as before, for multiple terminals. For one terminal, it is like this:
`Container.construct_confirm_close` has been significantly modified. The translation for "Close multiple terminals?" was broken and a …
=> Ask before closing, even if there is only one terminal

terminatorlib/plugins/custom_commands.py
- modified custom command plugin to have bookmarks
- made name parsing of the custom command optional, so whole command can be added instead of the command being auto split into sub-menus. Default behavior is kept and a checkbox option is provided.
- added keybindings for directly adding or launch the custom command menu
- the dialog window taking command for bookmark via shortcut keybinding will have focus on OK Button for faster interaction
After enabling plugin KeyBindings available for fast adding custom command `<Alt>b` to launch custom command pref menu `<Shift><Alt>b`
=> 706 favorites bookmarks plugin

terminatorlib/window.py
The current conditional always evaluates to False, resulting in the ungroup_win() function never being called
=> window.py: Fix window group toggle keybind

terminatorlib/config.py, terminatorlib/prefseditor.py, terminatorlib/terminal.py
- as per the bug the layout does not get updated when "Save" button in layout is pressed
- it does get updated if the window is closed by pressing top x close icon.
- on pressing Save, it seems that the prefseditor takes this from current_layout = terminator.describe_layout() and saves it in config
- whereas the current changes are done per key stroke and config is updated
- this patch copies the parameters like directory and command when Save is press and on_layoutrefreshbutton_clicked() is called
- Hence working dir and command are copied when Save is pressed using uuid to match terminals.
- If there is a command registered then the terminal runs the command and exits. so one is not able to see the results.
=> [bug 760] working directory feature is broken

terminatorlib/plugins/save_user_session_layout.py, terminatorlib/version.py
To overcome auto overwriting issues with the "SaveLastSessionLayout" plugin,
I added a "SaveUserSessionLayout" plugin, which provides a context menu item to trigger saving the current session to the default config file, thus preventing to be overwritten by the save on close of "SaveLastSessionLayout".
This session can then be restored with the terminator layout selector `terminator -s`.
This is useful to take a quick and simple snapshot of the current session for later re-use.
This implements feature request  #563.
=> feat: plugin - Save current user layout of all sessions, fixes #563

terminatorlib/terminator.py
- added get_vte().has_focus() for a valid focussed terminal to return
=> [bug 852] - 852-terminator_py_get_focussed_terminal_always_returns_none

terminatorlib/terminal.py
Got the following Warnings when running under python 3.12.1
home/mattrose/Code/terminator/terminatorlib/terminal.py:324: SyntaxWarning: invalid escape sequence '\['
hostchars = "-A-Za-z0-9:\[\]"
/home/mattrose/Code/terminator/terminatorlib/terminal.py:348: SyntaxWarning: invalid escape sequence '\.'
"(www|ftp)[" + hostchars + "]*\.[" + hostchars +
/home/mattrose/Code/terminator/terminatorlib/terminal.py:354: SyntaxWarning: invalid escape sequence '\.'
"[a-zA-Z0-9-]*\.[a-zA-Z0-9][a-zA-Z0-9-]+" +
/home/mattrose/Code/terminator/terminatorlib/terminal.py:359: SyntaxWarning: invalid escape sequence '\^'
"""news:[-A-Z\^_a-z{|}~!"#$%&'()*+,./0-9;:=?`]+@""" +
To fix this, I changed the strings to raw strings to pass to the regex
=> fix syntax warnings

terminatorlib/terminal.py
Previously, file URIs were lumped in with full uris that would be used for HTTP, FTP, etc.  This caused file:/// uri parser to ignore any file with a root dir that had a character that was not a valid hostname character to be ignored.
fixes #865
=> Properly parse file:/// URIs

terminatorlib/plugins/maven.py, terminatorlib/plugins/mousefree_url_handler.py, terminatorlib/plugins/url_handlers.py
Hello. I am a Void Linux package maintainer and I have noticed that terminator produces the following syntax warnings when issuing `python3 -m compileall`:
```
./usr/lib/python3.12/site-packages/terminatorlib/plugins/maven.py:35: SyntaxWarning: invalid escape sequence '\-'
maven_filters['apache_maven_plugin_artifact_id'] = 'maven\-(%(apache_maven_plugin_shortname)s)\-plugin' % maven_filters
./usr/lib/python3.12/site-packages/terminatorlib/plugins/maven.py:36: SyntaxWarning: invalid escape sequence '\-'
maven_filters['codehaus_maven_plugin_artifact_id'] = '(%(codehaus_maven_plugin_shortname)s)\-maven\-plugin' % maven_filters
./usr/lib/python3.12/site-packages/terminatorlib/plugins/maven.py:37: SyntaxWarning: invalid escape sequence '\.'
maven_filters['maven_plugin_version'] = …
```
=> Fix invalid escape sequences

terminatorlib/plugins/remote.py
A Terminator plugin which adds features for ssh and docker/podman to the context menu. 
Self contained and only relies on `psutil`. 
From the [terminator docs online](https://gnome-terminator.readthedocs.io/en/latest/plugins.html)
> Probably the most useful thing would be something to help customise Terminator for heavy ssh users
This will clone your current SSH/container session into a newly spawned terminal
Heavily inspired by [terminator_plugins](https://github.com/ilgarm/terminator_plugins) which is no longer maintained. My version doesn't need to subclass `Terminal` and only needs `vte.feed_child`
When you clone a remote session, you can apply a terminator profile based on host or container name
Inspired by [TerminatorHostWatch](https://github.com/GratefulTony/TerminatorHostWatch) …
=> Add plugin to clone ssh and container sessions when terminal is split

terminatorlib/terminal_popup_menu.py
The texts in popup menu are not translated correctly.
The gettext function should be placed together with the original text,
or it will not be detected by `./genpot.sh`.
I think this bug is introduced by #663.
=> fix translation in popup menu

terminatorlib/searchbar.py
- Fixed a bug where search is always initialized as case-sensitive, even if the "March Case" checkbox is unchecked.
- If search order is inverted, Shift+Enter will now search forward (instead of searching backward, which is the same direction as just pressing Enter).
- While we're at it, add some margin to the "Search:" label to improve how it looks
=> Searchbar improvements

terminatorlib/prefseditor.py
- KeyError when a single window layout is selected after selecting a multiple tab layouts second terminal as per issue #973 
- ensure that when the layout item is changed the layout sub item also gets reset to first item, else KeyError is thrown as described in bug
=> Ensure that when the layout item is changed the layout sub item also gets reset to first item, else KeyError is thrown

terminatorlib/plugins/command_notify.py
This prompts a crash with some versions of VTE and Python (see https://gitlab.gnome.org/GNOME/vte/-/issues/2858), and although the crash has been fixed in VTE, VTE's main developer said that creating an instance and connecting to a signal isn't the right way to do this check.  Use the test they recommend instead.
Fixes: #984
=> Clean up VTE notification-received signal check

terminatorlib/terminal.py
Resolved a bug where 'self.bgcolor.alpha' expected a number but received a string, causing a TypeError. The issue was traced to background darkness configuration handling.
=> Fix TypeError in reconfigure() of terminal.py (line 753)
