gnome-terminator/terminator

- .gitignore
- tests/test_doctests.py
- tests/testsignalman.py
It's not a big deal, but as it is part, maybe in the future we can improve these tests.
> Converting to python 3 and making all tests pass.

- .github/workflows/python.yml
To be clear, these are **very** basic checks, but we need to start somewhere.
> Add GitHub action for Python

- terminatorlib/terminal.py
Try the latest Vte functions, and fall back to Glib when this doesn't work.
This should fix problems with Ubuntu 17.10 and 18.04, where they avoided PCRE2 for Vte.
Can you give it a try @jest?
Tested:
followup for #10
> terminal: Improve compat for Vte Regex

- terminatorlib/regex.py
- terminatorlib/searchbar.py
- terminatorlib/terminal.py
This implements Regex support similar to #28, just for search.
@adnanhodzic, @yuriw please test this
fixes #4
> searchbar: Implement modern/glib regexp support

- terminatorlib/terminal.py
> Disable special logic for pasting on Wayland

- setup.py
Following advice from https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
> Install AppStream data as .metainfo.xml

- po/hr.po
- po/pl.po
- po/pt.po
- po/pt_BR.po
These were updated after the start of the GitHub project.
fixes #85
> Import Launchpad translations

- terminatorlib/config.py
- terminatorlib/preferences.glade
- terminatorlib/prefseditor.py
- terminatorlib/terminal.py
Added config option to select either PRIMARY or Clipboard for the PuTTY paste style option.
Reworked prefseditor .glade file to add the new option.
> Added putty_paste_style_source_clipboard

- terminatorlib/terminator.py
> replaces the handle_size property that was deprecated in gtk3.20

- terminatorlib/prefseditor.py
Finally got my head around git rebasing. Sorry for the other PR. This shouldn't have any additional merges.
> Fixed bug in prefseditor.py

- terminatorlib/regex.py
- terminatorlib/searchbar.py
Added regex flags to allow for caseless search
Added a Match Case checkbox to the search bar
Cleaned up a couple deprecation warnings in searchbar.py
> issue 44, add option for case sensitive search

- INSTALL.md
> add packages to install doc

- RELEASE.md
- terminatorlib/preferences.glade
It's where I would have expected it.
> Add version string to "Preferences -> About"

- terminatorlib/terminal.py
> add support for OSC-8

- README.md
Format shortcuts a little in the README
> Format shortcuts

- terminator
- terminatorlib/optionparse.py
> Dbus options

- terminatorlib/config.py
- terminatorlib/prefseditor.py
- terminatorlib/terminal.py
> add preferences keybindings

- INSTALL.md
> fix INSTALL instructions for setuptools

- terminatorlib/terminal.py
> only set clear background when background_image in config

- MANIFEST.in
> add tests to release tarball

- terminatorlib/config.py
- terminatorlib/preferences.glade
- terminatorlib/prefseditor.py
- terminatorlib/terminal.py
> Clear selection on smart copy

- terminator
> pass original working directory to dbus_options as well

- INSTALL.md
- MANIFEST.in
- README.md
- terminatorlib/util.py
One big patch for a bunch of small documentation issues that have been raised.
fixes #268 #274
> multiple small documentation fixes

- terminatorlib/plugins/command_notify.py
left some code in there that I was using to test, and it doesn't work as is.  This fixes
> fix stupid debugging error

- terminatorlib/terminal.py
fixes #178 
On most distros, this will do the right thing, most of the time
> support for SSH URIs

- po/de.po
- po/hr.po
Update, as discussed in issue **Update German and Croatian #69**, based upon current `terminator.pot` file.
BTW, for tranlsations, maybe you could consider using an online translation platform like Weblate, Poedit, Transifex, Launchpad (in the order of my preference). IMO, users are often potential translators! Sorry, I'm not a programmer, so I can't help with implementing it ...
> Update German and Croatian

- terminatorlib/plugin.py
- terminatorlib/terminal.py
Here are fixes for two minor fixes I stumbled on while doing some plugin development.
Cheers!
> Minor fixes

- terminator
- terminatorlib/ipc.py
- terminatorlib/optionparse.py
> add a commandline flag to unhide any windows

- terminatorlib/terminal.py
I try to solve #216, but it was more difficult than I imagined. So I just updated the code.
> feat: Migrating from hbox to GtkBox

- terminatorlib/terminal.py
starting refatoring the files.
> feat: refactoring terminal file

- terminatorlib/prefseditor.py
> fix 319: refresh layout after save

- RELEASE.md
> Update RELEASE docs

- AUTHORS
- CHANGELOG.md
- terminatorlib/preferences.glade
- terminatorlib/version.py
All the file changes necessary for release
> prep for release 2.1.0

- terminatorlib/terminal.py
> fix broadcast menu for sway and wayland

- .github/ISSUE_TEMPLATE/bug_report.md
I just wanted to clarify the wording around the config file, because I don't think it was clear.
> clarify config file sentences

- po/uk.po
Translated into Ukrainian. At 93%.
> Ukrainianized by 93%

- terminatorlib/notebook.py
> Incorrect layout sorting in notebook

- terminatorlib/notebook.py
Motivation: Most of the applications with tabs support such way of closing tabs.
> Closing tab on middle mouse button press

- terminatorlib/plugins/dir_open.py
Hello
I have created this simple plugin to add a feature I really missed in terminator.  
Simple opening current directory.
> Add new plugin for opening current directory using right mouse button

- terminatorlib/terminal.py
> tell titlebar to start focussed out if it does not have focus

- remotinator
- terminatorlib/ipc.py
- terminatorlib/terminal.py
> add bg_img and bg_img_all commands to remotinator

- setup.py
> remove gtk-update-icon-cache from setup.py

- terminatorlib/terminal_popup_menu.py
> add Set Window Title item to context menu

- terminatorlib/window.py
We use empty string for unset, not None
> Fix hide_window keybinding unset check

- terminator
> don't traceback while searching through /proc

- terminatorlib/terminal.py
- terminatorlib/terminal_popup_menu.py
> Add Readonly toggle to popup menu

- terminatorlib/plugins/insert_term_name.py
- terminatorlib/terminal.py
- terminatorlib/terminator.py
This plugin inserts the name of the terminal to the terminal itself. Implements #540
> Plugin and Group menu item that inserts the name of the terminal.

- terminatorlib/terminal.py
> fix drag and drop

- terminatorlib/config.py
- terminatorlib/notebook.py
- terminatorlib/preferences.glade
- terminatorlib/prefseditor.py
Just a common option could be found in other terminal
> add new tab after current tab option

- terminatorlib/configjson.py
Remove unused import of 'sys' module;
Fix typo in log message;
Removed unused variable in `get_layout()` method.
> fix: Minor fixes in terminatorlib/configjson.py

- terminatorlib/preferences.glade
- terminatorlib/prefseditor.py
Thanks to @Vulcalien doing the heavy lifting in #834.   I thought I'd whip up a preference GUI to make it more accessible.  
Thanks again @Vulcalien
> Ask before close gui

- terminatorlib/searchbar.py
Add keyboard binding for reverse search (<kbd>Shift</kbd> + <kbd>Return</kbd>)
> Add reverse search keyboard binding
